version: "3"
services:
  postgres:
    image:  postgres:9.6-alpine
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - ${COMPOSE_DB_PORT}
    ports:
      - ${COMPOSE_DB_PORT}:${COMPOSE_DB_PORT}
    environment:
      - POSTGRES_PASSWORD=${COMPOSE_DB_PW}
      - POSTGRES_USER=${COMPOSE_DB_NAME}
      - POSTGRES_DB=${COMPOSE_DB}
    networks:
      - mynet
    restart: unless-stopped
  # APP ------------------------------
  springbootapp:
    build: ""
    container_name: springbootapp
    expose:
      - ${COMPOSE_SPRING_SERVER_PORT}
    ports:
      - ${COMPOSE_SPRING_SERVER_PORT}:${COMPOSE_SPRING_SERVER_PORT}
    environment:
      JVM_OPTS: >
        -XX:NativeMemoryTracking=summary
        -XX:+StartAttachListener
        -XX:+UseSerialGC
        -Xss512k
        -Dcom.sun.management.jmxremote.rmi.port=8000
        -Dcom.sun.management.jmxremote=true
        -Dcom.sun.management.jmxremote.port=8000
        -Dcom.sun.management.jmxremote.ssl=false
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.local.only=false
        -Djava.rmi.server.hostname=localhost
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - mynet
volumes:
  postgres-data: {}

networks:
  mynet:
    driver: bridge
